/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-07-29 02:05:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class bodyiteratetag_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/attributetag.tld", Long.valueOf(1501293732281L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fmytag_005fpresent_0026_005fscope_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fmytag_005fbodyiterate_0026_005fscope_005fname_005fid;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fmytag_005fpresent_0026_005fscope_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fmytag_005fbodyiterate_0026_005fscope_005fname_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fmytag_005fpresent_0026_005fscope_005fname.release();
    _005fjspx_005ftagPool_005fmytag_005fbodyiterate_0026_005fscope_005fname_005fid.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head><title>Body iterate tag</title></head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

	List<String> all = new ArrayList<String>();
	all.add("one");
	all.add("two");
	all.add("three");
	request.setAttribute("all",all);
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      //  mytag:present
      com.lin.tag.AttributeTag _jspx_th_mytag_005fpresent_005f0 = (com.lin.tag.AttributeTag) _005fjspx_005ftagPool_005fmytag_005fpresent_0026_005fscope_005fname.get(com.lin.tag.AttributeTag.class);
      boolean _jspx_th_mytag_005fpresent_005f0_reused = false;
      try {
        _jspx_th_mytag_005fpresent_005f0.setPageContext(_jspx_page_context);
        _jspx_th_mytag_005fpresent_005f0.setParent(null);
        // /bodyiteratetag.jsp(14,1) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_mytag_005fpresent_005f0.setName("all");
        // /bodyiteratetag.jsp(14,1) name = scope type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_mytag_005fpresent_005f0.setScope("request");
        int _jspx_eval_mytag_005fpresent_005f0 = _jspx_th_mytag_005fpresent_005f0.doStartTag();
        if (_jspx_eval_mytag_005fpresent_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t");
            //  mytag:bodyiterate
            com.lin.tag.BodyIterateTag _jspx_th_mytag_005fbodyiterate_005f0 = (com.lin.tag.BodyIterateTag) _005fjspx_005ftagPool_005fmytag_005fbodyiterate_0026_005fscope_005fname_005fid.get(com.lin.tag.BodyIterateTag.class);
            boolean _jspx_th_mytag_005fbodyiterate_005f0_reused = false;
            try {
              _jspx_th_mytag_005fbodyiterate_005f0.setPageContext(_jspx_page_context);
              _jspx_th_mytag_005fbodyiterate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_mytag_005fpresent_005f0);
              // /bodyiteratetag.jsp(15,2) name = id type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_mytag_005fbodyiterate_005f0.setId("url");
              // /bodyiteratetag.jsp(15,2) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_mytag_005fbodyiterate_005f0.setName("all");
              // /bodyiteratetag.jsp(15,2) name = scope type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_mytag_005fbodyiterate_005f0.setScope("request");
              int _jspx_eval_mytag_005fbodyiterate_005f0 = _jspx_th_mytag_005fbodyiterate_005f0.doStartTag();
              if (_jspx_eval_mytag_005fbodyiterate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                java.lang.String url = null;
                if (_jspx_eval_mytag_005fbodyiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_mytag_005fbodyiterate_005f0);
                }
                url = (java.lang.String) _jspx_page_context.findAttribute("url");
                do {
                  out.write("\r\n");
                  out.write("\t\t\t<h3>number: ");
                  out.print(url);
                  out.write("</h3>\r\n");
                  out.write("\t\t");
                  int evalDoAfterBody = _jspx_th_mytag_005fbodyiterate_005f0.doAfterBody();
                  url = (java.lang.String) _jspx_page_context.findAttribute("url");
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_mytag_005fbodyiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_mytag_005fbodyiterate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fmytag_005fbodyiterate_0026_005fscope_005fname_005fid.reuse(_jspx_th_mytag_005fbodyiterate_005f0);
              _jspx_th_mytag_005fbodyiterate_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_mytag_005fbodyiterate_005f0, _jsp_getInstanceManager(), _jspx_th_mytag_005fbodyiterate_005f0_reused);
            }
            out.write('\r');
            out.write('\n');
            out.write('	');
            int evalDoAfterBody = _jspx_th_mytag_005fpresent_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_mytag_005fpresent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fmytag_005fpresent_0026_005fscope_005fname.reuse(_jspx_th_mytag_005fpresent_005f0);
        _jspx_th_mytag_005fpresent_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_mytag_005fpresent_005f0, _jsp_getInstanceManager(), _jspx_th_mytag_005fpresent_005f0_reused);
      }
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
